---
- hosts: ucp
  gather_facts: false
  connection: local
  user: remote
  become: true

  vars_files:
    - vars.yml

  tasks:
    - name: Reconfigure CPU and RAM specs
      vsphere_guest:
        vcenter_hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        cluster: "{{ cluster }}"
        guest: "{{ inventory_hostname }}"
        state: reconfigured
        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd: yes
        vm_hardware:
          memory_mb: 8192
          num_cpus: 2
        esxi:
          datacenter:  "{{ datacenter }}"
          hostname: "{{ esxi_host }}"
