---
- hosts: all
  gather_facts: false
  connection: local
  user: remote
  become: true

  vars_files:
    - vars.yml
    - enc_vars.yml

  tasks:
    - name: Reconfigure CPU and RAM specs on UCP hosts
      vsphere_guest:
        vcenter_hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        cluster: "{{ cluster }}"
        guest: "{{ inventory_hostname }}"
        state: reconfigured
        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd: yes
        vm_hardware:
          memory_mb: "{{ ucp_ram }}"
          num_cpus: "{{ ucp_cpus }}"
        vm_disk:
          disk2:
            size_gb: "{{ ucp_disk2_size }}"
            type: thin
            datastore: "{{ datastores | random }}"
        esxi:
          datacenter:  "{{ datacenter }}"
          hostname: "{{ esxi_host }}"
      when: inventory_hostname in groups.ucp

    - name: Reconfigure CPU and RAM specs on workers and DTR hosts
      vsphere_guest:
        vcenter_hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        cluster: "{{ cluster }}"
        guest: "{{ inventory_hostname }}"
        state: reconfigured
        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd: yes
        vm_hardware:
          memory_mb: "{{ dtr_ram }}"
          num_cpus: "{{ dtr_cpus }}"
        vm_disk:
          disk2:
            size_gb: "{{ dtr_disk2_size }}"
            type: thin
            datastore: "{{ datastores | random }}"
        esxi:
          datacenter:  "{{ datacenter }}"
          hostname: "{{ esxi_host }}"
      when: inventory_hostname in groups.dtr or inventory_hostname in groups.worker

    - name: Reconfigure CPU and RAM specs on Load Balancers
      vsphere_guest:
        vcenter_hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        cluster: "{{ cluster }}"
        guest: "{{ inventory_hostname }}"
        state: reconfigured
        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd: yes
        vm_hardware:
          memory_mb: "{{ lb_ram }}"
          num_cpus: "{{ lb_cpus }}"
        esxi:
          datacenter:  "{{ datacenter }}"
          hostname: "{{ esxi_host }}"
      when: inventory_hostname in groups.lbs
