---
- hosts: ucp,dtr,worker
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - vars.yml

  tasks:
    - name: Open required ports for UCP
      command: firewall-cmd --permanent --zone=public --add-port=443/tcp --add-port=2376/tcp --add-port=2377/tcp --add-port=4789/tcp --add-port=4789/udp --add-port=7946/tcp --add-port=7946/udp --add-port=12376/tcp --add-port=12379/tcp --add-port=12380/tcp --add-port=12381/tcp --add-port=12382/tcp --add-port=12383/tcp --add-port=12384/tcp --add-port=12385/tcp --add-port=12386/tcp --add-port=12387/tcp
      when: inventory_hostname in groups.ucp

    - name: Open required ports for DTR
      command: firewall-cmd --permanent --zone=public --add-port=80/tcp --add-port=443/tcp --add-port=2377/tcp --add-port=4789/tcp --add-port=4789/udp --add-port=7946/tcp --add-port=7946/udp --add-port=12376/tcp
      when: inventory_hostname in ['groups.dtr','groups.worker']

    - name: Reload firewalld configuration
      command: firewall-cmd --reload

    - name: Restart docker service
      systemd:
        name: docker
        state: restarted

    - name: Install swarm leader and first UCP node
      command: docker run --rm --name ucp -v /var/run/docker.sock:/var/run/docker.sock docker/ucp install --host-address {{ ip_addr | ipaddr('address') }} --admin-username=admin --admin-password={{ vm_pw }} --san dp-ucp-lb.am2.cloudra.local --san dp-ucp01.am2.cloudra.local --san dp-ucp02.am2.cloudra.local --san dp-ucp03.am2.cloudra.local --san 10.10.174.63 --san 10.10.174.64 --san 10.10.174.65
      register: output
      when: inventory_hostname == 'dp-ucp01'
      failed_when: output.rc > 1

    - name: Get swarm manager token
      shell: echo `docker swarm join-token manager` | cut -f2 -d':' | sed 's|\\||g'
      register: manager_token
      when: inventory_hostname == 'dp-ucp01'

    - name: Get swarm worker token
      shell: echo `docker swarm join-token worker` | cut -f2 -d':' | sed 's|\\||g'
      register: worker_token
      when: inventory_hostname == 'dp-ucp01'

    - debug:
        msg: "{{ hostvars['dp-ucp01'] }}"
      when: inventory_hostname == 'dp-ucp01'

    - name: Add additional UCP nodes to the swarm
      command: "{{ hostvars['dp-ucp01']['manager_token']['stdout'] }}"
      when: inventory_hostname in ['dp-ucp02','dp-ucp03']

    - name: Add DTR and Worker nodes to the swarm
      command: "{{ hostvars['dp-ucp01']['worker_token']['stdout'] }}"
      when: inventory_hostname in ['dp-dtr01','dp-dtr02','dp-dtr03','dp-worker01','dp-worker02','dp-worker03']

    - name: Wait for all services to start up properly
      pause:
        minutes: 3

    - name: Install first DTR node
      command: docker run --rm docker/dtr:2.2.5 install --ucp-node {{ inventory_hostname }}.{{ domain_name }} --ucp-insecure-tls --dtr-external-url https://dp-dtr-lb.am2.cloudra.local:443 --ucp-url https://dp-ucp01.am2.cloudra.local:443 --ucp-username admin --ucp-password {{ vm_pw }}
      # command: docker run --rm docker/dtr:2.2.5 install --ucp-node {{ inventory_hostname }} --ucp-insecure-tls --dtr-external-url https://dp-dtr-lb.am2.cloudra.local:443 --ucp-url https://10.10.174.63:443 --ucp-username admin --ucp-password {{ vm_pw }}
      when: inventory_hostname == 'dp-dtr01'
      register: dtrlog

    - name: Grab DTR flag from output
      shell: echo "{{ dtrlog.stdout }}" | grep 'You can use flag'| cut -d "'" -f2
      when: inventory_hostname == 'dp-dtr01'
      register: flag

    - name: Add DTR nodes
      command: docker run --rm docker/dtr:2.2.5 join --ucp-node {{ inventory_hostname }}.{{ domain_name }} -ucp-url https://dp-ucp01.am2.cloudra.local:443 --ucp-username admin --ucp-password {{ vm_pw }} --ucp-insecure-tls {{ hostvars['dp-dtr01']['flag']['stdout'] }}
      when: inventory_hostname in ['dp-dtr02','dp-dtr03']
