---
# This playbook will create a Docker UCP environment

- include: create_vms.yml
- include: change_vm_specs.yml
- include: power_on_guests.yml
- include: config_networking.yml
- include: distribute_keys.yml
- include: install_haproxy.yml
- include: config_lvs.yml
- include: start_docker.yml
- include: install_ucp_nodes.yml
