---
# This playbook will create a Docker UCP environment

- include: create_vms.yml
- include: create_lbs.yml
- include: change_ucp_specs.yml
- include: change_dtr_specs.yml
- include: change_worker_specs.yml
- include: change_lbs_specs.yml
- include: config_docker_nodes.yml
