---
- hosts: all
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - vars.yml

  tasks:
    - name: print to stdout
      command: hostname
      register: hello

    - debug: msg="{{ hello.stdout }}"
