---
- hosts: dp-worker01
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - vars.yml

  tasks:
    - name: Save worker token
      local_action: copy content="token{{ ":" }} {{ inventory_hostname }}" dest=/tmp/test
