---
- hosts: docker
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - vars.yml

  tasks:
    - debug: msg="{{ hostvars[inventory_hostname]['groups']['ucp_main'][0]['manager_token']['stdout'] }}"
