---
- hosts: all
  gather_facts: false
  connection: local
  user: remote
  become: true

  vars_files:
    - ../group_vars/vars
    - ../group_vars/vault

  tasks:
    - name: Create all VMs
      vsphere_guest:
        vcenter_hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        cluster: "{{ cluster }}"
        guest: "{{ inventory_hostname }}"
        from_template: yes
        template_src: "{{ vm_template }}"
        power_on_after_clone: no
        vm_extra_config:
          folder: "{{ folder_name }}"
        esxi:
          datacenter: "{{ datacenter }}"
          hostname: "{{ esxi_host }}"
