---
- hosts: vms
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ../group_vars/vars

  environment: "{{ env }}"

  tasks:
    - name: Install NTP
      yum:
        name: ntp
        state: latest

    - name: Update ntp.conf
      template:
        src: ../templates/ntp.conf.j2
        dest: /etc/ntp.conf
        owner: root
        group: root
        mode: 0644        
      notify: Enable and restart NTP service

  handlers:
    - name: Enable and restart NTP service
      systemd:
        name: ntpd
        enabled: yes
        state: restarted
