---
- hosts: lbs
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ../group_vars/vars

  environment: "{{ env }}"

  tasks:
    - name: Open http and https ports
      command: firewall-cmd --permanent --zone=public --add-port=80/tcp --add-port=443/tcp

    - name: Reload firewalld configuration
      command: firewall-cmd --reload

    - name: Install haproxy
      yum:
        name: haproxy
        state: latest

    - name: Update haproxy.cfg on Worker Load Balancer
      template:
        src: ../templates/haproxy.cfg.worker.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0644        
      when: inventory_hostname in groups.worker_lb
      notify: Enable and start haproxy service

    - name: Update haproxy.cfg on UCP Load Balancer
      template:
        src: ../templates/haproxy.cfg.ucp.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0644
      when: inventory_hostname in groups.ucp_lb
      notify: Enable and start haproxy service

    - name: Update haproxy.cfg on DTR Load Balancer
      template:
        src: ../templates/haproxy.cfg.dtr.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0644
      when: inventory_hostname in groups.dtr_lb
      notify: Enable and start haproxy service

  handlers:
    - name: Enable and start haproxy service
      systemd:
        name: haproxy
        enabled: yes
        state: restarted
