---
- hosts: lbs
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ../group_vars/vars

  environment: "{{ env }}"

  tasks:
    - name: Install haproxy
      yum:
        name: haproxy
        state: latest

    - name: Updating haproxy.cfg on Worker Load Balancer
      template:
        src: ../templates/haproxy.cfg.app.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0644        
      when: inventory_hostname in groups.app_lb

    - name: Updating haproxy.cfg on UCP Load Balancer
      template:
        src: ../templates/haproxy.cfg.ucp.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0644
      when: inventory_hostname in groups.ucp_lb

    - name: Updating haproxy.cfg on DTR Load Balancer
      template:
        src: ../templates/haproxy.cfg.dtr.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0644
      when: inventory_hostname in groups.dtr_lb

    - name: Enable and start haproxy service
      systemd:
        name: haproxy
        enabled: yes
        state: started

    - name: Open http and https ports
      command: firewall-cmd --permanent --zone=public --add-port=80/tcp --add-port=443/tcp

    - name: Reload firewalld
      command: firewall-cmd --reload
