---
- hosts: dtr
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ../group_vars/vars

  environment: "{{ env }}"

  tasks:
    - name: Install NFS client
      yum:
        name: nfs-utils
        state: latest
