---
- hosts: lbs
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ../vars.yml

  environment: "{{ env }}"

  tasks:
    - name: Install haproxy
      yum:
        name: haproxy
        state: latest

    - name: Updating haproxy.cfg
      template:
        src: ../templates/haproxy.cfg.{{ inventory_hostname }}.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0644        

    - name: Enable and start haproxy service
      systemd:
        name: haproxy
        enabled: yes
        state: started

    - name: Open http and https ports
      command: firewall-cmd --permanent --zone=public --add-port=80/tcp --add-port=443/tcp

    - name: Reload firewalld
      command: firewall-cmd --reload
